#!/usr/bin/env bash

_file=$1

function burn() {
    ${ARM_BURNER}/ccs_base/DebugServer/bin/DSLite flash -e -v \
        -c ${ARM_BURNER}/user_files/configs/msp432p401r.ccxml \
        -l ${ARM_BURNER}/user_files/settings/generated.ufsettings \
        -f $_file
}

echo "Preparing to burn file $_file..."
burn
